name:                rocksdb-query
version:             0.4.0
github:              "jprupp/rocksdb-query"
license:             MIT
license-file:        LICENSE
author:              "Jean-Pierre Rupp"
maintainer:          "jprupp@protonmail.ch"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis:            RocksDB database querying library for Haskell
category:            Database

description:         Please see the README on GitHub at <https://github.com/jprupp/rocksdb-query#readme>

dependencies:
  - base >= 4.7 && < 5
  - cereal
  - unliftio
  - rocksdb-haskell-jprupp

library:
  source-dirs: src
  dependencies:
    - bytestring
    - conduit
    - resourcet

tests:
  rocksdb-query-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - data-default
      - rocksdb-query
      - hspec
